kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: ZAmhV7XF6WaHtqXOGffWJ5XESvg/CdrSP5DA6MpHo18=
      - identity: {}
