global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#andrey-kuznetsov'
