version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:${DB_PATH}
    networks:
      back_net:
        aliases:
          - comment_db
  ui:
    image: ${REGISTRY_USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - front_net
  post:
    image: ${REGISTRY_USERNAME}/post:${POST_VERSION}
    networks:
      - back_net
      - front_net
  comment:
    image: ${REGISTRY_USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  front_net:
  back_net: