version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:${DB_PATH}
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${REGISTRY_USERNAME}/ui:${UIVERSION}
    ports:
      - ${UIPORT}:9292/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${REGISTRY_USERNAME}/post:${POSTVERSION}
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${REGISTRY_USERNAME}/comment:${COMMENTVERSION}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  front_net:
  back_net: